---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: boot-node-prater-jato-v1
  namespace: REPLACE_NAMESPACE
spec:
  hosts:
  - "boot-node-prater-jato-v1.REPLACE_DOMAIN_SUFFIX"
  gateways:
  - boot-node-prater-jato-v1
  http:
  - route:
    - destination:
        host: boot-node-prater-jato-v1-svc
        port:
          number: 5000
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: boot-node-prater-jato-v1
  namespace: REPLACE_NAMESPACE
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "boot-node-prater-jato-v1.REPLACE_DOMAIN_SUFFIX"
---
apiVersion: v1
kind: Service
metadata:
  name: boot-node-prater-jato-v1-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: boot-node-prater-jato-v1
spec:
  type: ClusterIP
  ports:
    - port: 5679
      protocol: TCP
      targetPort: 5679
      name: port-5679
    - port: 4000
      protocol: UDP
      targetPort: 4000
      name: port-4000
    - port: 5000
      protocol: TCP
      targetPort: 5000
      name: port-5000
  selector:
    app: boot-node-prater-jato-v1
---
apiVersion: REPLACE_API_VERSION 
kind: Deployment
metadata:
  labels:
    app: boot-node-prater-jato-v1
  name: boot-node-prater-jato-v1
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: boot-node-prater-jato-v1
  template:
    metadata:
      labels:
        app: boot-node-prater-jato-v1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/role
                operator: In
                values:
                - ssv-boot-node
      containers:
      - name: boot-node-prater-jato-v1
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG 
        imagePullPolicy: Always
        command: ["make", "start-boot-node"]
        ports:
        - containerPort: 5000
          name: port-5000      
          hostPort: 5000
        env:
          - name: BOOT_NODE_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: config-secrets
                key: boot_node_private_key
          - name: BOOT_NODE_EXTERNAL_IP
            valueFrom:
              secretKeyRef:
                name: config-secrets
                key: boot_node_external_ip
          - name: TCP_PORT
            value: "5000"
          - name: UDP_PORT
            value: "4000"
        volumeMounts:
        - mountPath: /data/bootnode
          name: boot-node-prater-jato-v1
      volumes:
      - name: boot-node-prater-jato-v1
        persistentVolumeClaim:
          claimName: boot-node-prater-jato-v1
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/role
        operator: Exists         
      hostNetwork: true
