---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ssv-full-node-prater-jato-v1-1
  namespace: REPLACE_NAMESPACE
spec:
  hosts:
  - "ws-ssv-full-node-prater-jato-v1-1.REPLACE_DOMAIN_SUFFIX"
  gateways:
  - ssv-full-node-prater-jato-v1-1
  http:
  - route:
    - destination:
        host: ssv-full-node-prater-jato-v1-1
        port:
          number: 14000
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ssv-full-node-prater-jato-v1-1
  namespace: REPLACE_NAMESPACE
spec:
  selector:
    istio: ingressgateway-int
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "ws-ssv-full-node-prater-jato-v1-1.REPLACE_DOMAIN_SUFFIX"
---
apiVersion: v1
kind: Service
metadata:
  name: ssv-full-node-prater-jato-v1-1
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-full-node-prater-jato-v1-1
spec:
  type: ClusterIP
  ports:
    - port: 12000
      protocol: UDP
      targetPort: 12000
      name: port-12000
    - port: 13000
      protocol: TCP
      targetPort: 13000
      name: port-13000
    - port: 14000
      protocol: TCP
      targetPort: 14000
      name: port-14000
    - port: 15000
      protocol: TCP
      targetPort: 15000
      name: port-15000
  selector:
    app: sssv-full-node-prater-jato-v1-1
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-full-node-prater-jato-v1-1
  name: ssv-full-node-prater-jato-v1-1
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-full-node-prater-jato-v1-1
  template:
    metadata:
      labels:
        app: ssv-full-node-prater-jato-v1-1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - ssv-main
                  - key: beta.kubernetes.io/instance-type
                    operator: In
                    values:
                      - m5a.4xlarge
      containers:
      - name: ssv-full-node-prater-jato-v1-1
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
        imagePullPolicy: Always
        resources:
          limits:
            cpu: REPLACE_EXPORTER_CPU_LIMIT
            memory: REPLACE_EXPORTER_MEM_LIMIT
        command: ["make", "start-node"]
        ports:
        - containerPort: 12000
          name: port-12000
          hostPort: 12000
          protocol: UDP
        - containerPort: 13000
          name: port-13000
          hostPort: 13000
        - containerPort: 14000
          name: port-14000
          hostPort: 14000
        - containerPort: 15000
          name: port-15000
          hostPort: 15000
        env:
          - name: SHARE_CONFIG
            value: "./data/share.yaml"
          - name: ETH_1_ADDR
            valueFrom:
              secretKeyRef:
                name: config-secrets
                key: eth1_addr
          - name: BOOTNODES
            valueFrom:
              secretKeyRef:
                name: config-secrets
                key: bootnodes
          - name: LOG_LEVEL
            value: "debug"
          - name: DB_REPORTING
            value: "false"
          - name: PUBSUB_TRACE
            value: "false"
          - name: DISCOVERY_TYPE_KEY
            value: "discv5"
          - name: NETWORK
            value: "prater"
          - name: DB_PATH
            value: "./data/db-jato-v1"
          - name: METRICS_API_PORT
            value: "15000"
          - name: ENABLE_PROFILE
            value: "true"
          - name: GENERATE_OPERATOR_KEY
            value: "true"
          - name: UDP_PORT
            value: "12000"
          - name: TCP_PORT
            value: "13000"
          - name: WS_API_PORT
            value: "14000"
          - name: FULLNODE
            value: "true"
          - name: MSG_WORKERS_COUNT
            value: "1024"
          - name: MSG_WORKER_BUFFER_SIZE
            value: "2048"
          - name: SUBNETS
            value: "0xffffffffffffffffffffffffffffffff"
          - name: P2P_MAX_PEERS
            value: "300"
        volumeMounts:
        - mountPath: /data
          name: ssv-full-node-prater-jato-v1-1
        - mountPath: /data/share.yaml
          subPath: share.yaml
          name: ssv-full-node-prater-jato-v1-1-cm
      volumes:
      - name: ssv-full-node-prater-jato-v1-1
        persistentVolumeClaim:
          claimName: ssv-full-node-prater-jato-v1-1
      - name: ssv-full-node-prater-jato-v1-1-cm
        configMap:
          name: ssv-full-node-prater-jato-v1-1-cm
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/role
          operator: Exists
      hostNetwork: true
